server {
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Clickjacking protection
    add_header X-Frame-Options "DENY" always;
    add_header Content-Security-Policy "frame-ancestors 'none';" always;

    location / {
        try_files $uri $uri/ /index.html;
    }
}