name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Generate version.json
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          cat > public/version.json <<EOF
          {
            "version": "${{ github.sha }}",
            "displayVersion": "v1.0.${{ github.run_number }}",
            "commit": "$SHORT_SHA",
            "buildTime": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          }
          EOF

      - name: Build Angular Application
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t sambidhan026/image-upload-web:latest .

      - name: Push Docker Image
        run: docker push sambidhan026/image-upload-web:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user
            docker-compose pull
            docker-compose up -d